version: "3"
services:
  app:
    container_name: appTeste
    restart: always
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./apps:/app
    links:
      - mongo
  mongo:
    container_name: mongoTeste
    image: mongo
    volumes:
      - ./database/mongo:/data/db
    ports:
      - "27017:27017"