version: "3"
services:
  app:
    container_name: appTeste
    restart: always
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps:/app
    links:
      - mongo
  mongo:
    container_name: mongoTeste
    image: mongo
    volumes:
      - ./database/mongo:/data/db
    ports:
      - "3000:27017"
